# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b3d1a5d27db2016413606bcae97ef2f1e715ee479d3299ac1867f4f53a339f1765d6f5236fda7c390f735a2aab1ce20da65b682e5dc3eb2e4eef0a8f6d07160

test:
  secret_key_base: e83f848141ba73a84dbcbd15f0f9d31aeb635267c17bd18b3eadee1318e599c8dc83538f3f74b8a507ee8c0e943f046c684142a7c7e5a91bf8332853b70e198b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
